# MySQL address, user and password
# user must have replication privilege in MySQL.
#my_addr = "wiz-database-prod-cluster.cluster-ro-cfqo6cjytuk4.us-west-1.rds.amazonaws.com:5378"
my_addr = "wiz-database-prod-cluster.cluster-cfqo6cjytuk4.us-west-1.rds.amazonaws.com:5378"
my_user = "unicorndb"
my_pass = "vidueyr73854*%"
my_charset = "utf8"

# Set true when elasticsearch use https
es_https = true
# Elasticsearch address
es_addr = "vpc-lookwide-production-boagolljhfg6hbpffswwkbbhby.us-west-1.es.amazonaws.com"
# Elasticsearch user and password, maybe set by shield, nginx, or x-pack
es_user = ""
es_pass = ""
# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing.
# TODO: support other storage, like etcd.
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
skip_master_data = true

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

# Ignore table without primary key
skip_no_pk_table = true

# MySQL data source
[[source]]
schema = "wiz"
tables = ["user", "expertise", "question", "audio_post"]

# Below is for special rule mapping
[[rule]]
schema = "wiz"
table = "user"
index = "user"
type = "user"
# Only sync following columns
filter = ["id", "first_name", "last_name", "headline", "bio", "region", "ranking"]

[rule.field]
first_name = "firstName"
last_name = "lastName"

[[rule]]
schema = "wiz"
table = "expertise"
index = "expertise"
type = "expertise"
filter = ["id", "title", "ranking"]

[[rule]]
schema = "wiz"
table = "question"
index = "question"
type = "question"
# Only sync following columns
filter = ["id", "title", "detail", "allow_public", "status"]

[rule.field]
allow_public = "allowPublic"

[[rule]]
schema = "wiz"
table = "audio_post"
index = "audio_post"
type = "audio_post"
# Only sync following columns
filter = ["id", "subject"]